### ISSUE TITLE
Patch to work with 2.7

### ISSUE THREAD

**Issue by isigaesc** [pfmooney/puppet-mit_krb5#1]
It seems that scope.include? and scope[] don't work in Debian stable (2.7).
Error messages are like:

```
   Failed to parse template mit_krb5/libdefaults.erb:
     Filepath: /usr/lib/ruby/vendor_ruby/puppet/parser/scope.rb
     Line: 459
     Detail: undefined method `each' for #<Puppet::Parser::Scope:0xb58ce3e8>
    at /etc/puppet/modules/mit_krb5/manifests/init.pp:274
```

It apparently works with the following changes:

```
diff -r -u5 /tmp/mit_krb5/templates/libdefaults.erb mit_krb5/templates/libdefaults.erb
--- /tmp/mit_krb5/templates/libdefaults.erb     2013-12-07 20:34:44.000000000 +0000
+++ mit_krb5/templates/libdefaults.erb  2014-03-14 14:54:51.000000000 +0000
@@ -30,12 +30,12 @@
   'rdns',
   'plugin_base_dir',
 ]
 output = []
 fields.each do |key|
-  next if not scope.include?(key)
-  value = scope[key]
+  next if not scope.to_hash.include?(key)
+  value = scope.to_hash[key]
   if value.respond_to?('join')
     # Use space delimiting for array-type values
     value = value.flatten.join(' ')
   else
     value = value.to_s
diff -r -u5 /tmp/mit_krb5/templates/logging.erb mit_krb5/templates/logging.erb
--- /tmp/mit_krb5/templates/logging.erb 2013-12-07 20:34:44.000000000 +0000
+++ mit_krb5/templates/logging.erb      2014-03-14 14:55:14.000000000 +0000
@@ -1,10 +1,10 @@
 <% fields = ['default', 'admin_server', 'kdc']
 output = []
 fields.each do |k|
-  if scope.include? k and not scope[k].empty?
-    value = scope[k]
+  if scope.to_hash.include? k and not scope.to_hash[k].empty?
+    value = scope.to_hash[k]
     # Preserve array-type values
     if value.respond_to?('each')
       value.flatten! if value.respond_to?('flatten')
       value.each do |v|
         output.push("#{k} = #{v}")
diff -r -u5 /tmp/mit_krb5/templates/realm.erb mit_krb5/templates/realm.erb
--- /tmp/mit_krb5/templates/realm.erb   2013-12-07 20:34:44.000000000 +0000
+++ mit_krb5/templates/realm.erb        2014-03-14 15:18:01.000000000 +0000
@@ -9,12 +9,12 @@
     'auth_to_local'
 ]
 array_fields = ['kdc', 'admin_server']
 output = []
 fields.each do |k|
-  if scope.include?(k)
-    value = scope[k]
+  if scope.to_hash.include?(k)
+    value = scope.to_hash[k]
     if array_fields.include? k and value.respond_to?('each')
       # Allow multiple servers via array
       value.flatten! if value.respond_to?('flatten')
       value.each do |v|
         output.push("#{k} = #{v}")

```

Thanks for the module!
